spring:
  datasource:
    url: jdbc:mysql://your-prod-host:3306/aquainsight_prod?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: your-username
    password: your-password

logging:
  level:
    root: INFO
    com.aquainsight: INFO
