spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aquainsight_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    root: DEBUG
    com.aquainsight: DEBUG
